# Generated by Django 4.1.13 on 2024-03-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_tags_post_all_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='all_tags',
            new_name='tags',
        ),
    ]
